### ISSUE TITLE
偶像

### ISSUE THREAD

**Issue by HuoJiangJiang** [niyaoyao/react-native-redux-app#1]
偶像，女神。

**Comment by niyaoyao** [comment]
二货

倪瑶（N.Y.） 上海-iOS工程师，ELEME Inc.
Email:yao.ni@ele.me | Mobile: 18766120890
http://ele.me 饿了么

On November 16, 2016 at 3:10:18 PM, 阿争 (notifications@github.com) wrote:

偶像，女神。

**Comment by niyaoyao** [comment]
。。。。。跪了。。。
